# Change these first
owner: cavalicenti # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Artfos
    url: https://www.artfos.com.ar
  - name: Artfos ERP
    url: https://intranet.artfos.com.ar/
  - name: OCEBA frontend
    url: https://conreg-fe.oceba.gba.gov.ar
  - name: OCEBA Backend
    url: https://conreg-be.oceba.gba.gov.ar
  - name: Albanesi Backend
    url: http://proveedores.albanesi.com.ar/web/index.php/site/login
  - name: Albanesi Frontend
    url: http://proveedores.albanesi.com.ar
  - name: BA Anglers
    url: https://www.buenosairesanglers.com/
  - name: Janax Soft
    url: https://www.janaxsoftware.com.ar/
  - name: Mas Valores
    url: https://www.masvalores.com.ar/
  - name: TR66
    url: https://www.transportesruta66.com.ar/
assignees: # Users to assign downtime issues (optional)
  - cavalicenti
status-website:
  theme: ocean
  favicon: https://www.artfos.com.ar/wp-content/uploads/2018/05/cropped-artfos_marcaB-1-e1527704779510-32x32.png
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://www.artfos.com.ar/wp-content/uploads/2019/11/logoweb2.png
  name: Estado webs
  introTitle: "Estado de aplicaciones."
  introMessage: "**Artfos S.A** este es el estado de las aplicaciones monitoreadas por Artfos"
  navbar:
    - title: Estado
      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
    - title: PortalDesa
      href: https://sites.google.com/artfos.com.ar/portal-desarrollo/home

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
