# Change these first
owner: cavalicenti # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Artfos
    url: https://www.artfos.com.ar
  - name: OCEBA frontend
    url: https://conreg-fe.oceba.gba.gov.ar
  - name: OCEBA Backend
    url: https://conreg-be.oceba.gba.gov.ar
  - name: Albanesi Backend
    url: http://proveedores.albanesi.com.ar:8081/web/index.php/site/login
  - name: Albanesi Frontend
    url: http://proveedores.albanesi.com.ar:8081

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Estado de aplicaciones."
  introMessage: "**Artfos S.A** este es el estado de las aplicaciones en la infraestructura de OCEBA monitoreadas por Artfos"
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: PortalDesa
      href: https://sites.google.com/artfos.com.ar/portal-desarrollo/home

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
